### PR TITLE
Alexandreelise french translation

### PR DESCRIPTION
**Pull request by alexandreelise**

### CODE REVIEW

**Review by yiendos — APPROVED** [review]
Hi @alexandreelise, this looks great, many thanks for taking the time to contribute. It is very much appreciated.

**Comment by yiendos** [comment]
@alexandreelise on a personal note,it's the first time anybody has ever opened a PR request against my work. A proud developer day for me :). Thank you very much

**Comment by yiendos** [comment]
@alexandreelise ooo also back ported your wiki page into this repository:
https://github.com/joomlatools/joomlatools-gitpod/wiki

Thanks for the contributions!

**Comment by alexandreelise** [comment]
@yiendos Your work is awesome Paul. I like devops oriented geeky stuff. joomlatools gitpod is the compound beauty of testing, docker, cli and joomla 4. Simply the best tool to not waste time uselessly. Right to the point. Thanks again Paul.

**Pull request merged**
